/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gwaekeqhrihbhhiezupg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3YWVrZXFocmloYmhoaWV6dXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxNjQ3NzIsImV4cCI6MjA3ODc0MDc3Mn0.--tnWp-Dzmie0L8ReOEoKgWKvrXC2jNPzMx6UsNGIxs"